### PR TITLE
docs: improve documentation with plots

### PR DESCRIPTION
**Pull request by redeboer**
Summary of changes:
* Removed text about downloading the notebook, because this is already proivded by the Sphinx Book theme.
* Explained a bit more about the example decay channel
* Use all _f0_ resonances in the example decay channel
* Show how to convert the state IDs to particle names
* Illustrate how to plot the fit result with `matplotlib`
* Added a snippet that shows how to indicate the resonance positions in the plots
* Added a snippet for exporting the fit result (but it's not yet used to import it back)

### CODE REVIEW

**Comment by redeboer** [comment]
@Leongrim @sebastianJaeger These changes additions are to help you guys, could you have a look?

@spflueger You can have a look as well, but I did not modify the source code.

**Comment by redeboer** [comment]
So for the record: best to review the rendered pages
https://pwa--142.org.readthedocs.build/projects/tensorwaves/en/142/usage.html

You can also download the notebooks from there (upper right) and run them yourself to see if you would like to add some more code snippets that are interesting to the physicist. (Better would of course be to checkout the branch of this PR.)

**Comment by Leongrim** [comment]
In <a href="https://pwa--142.org.readthedocs.build/projects/tensorwaves/en/142/usage/2_generate_data.html">Step 2</a> it is mentioned that not all the invariant masses are registered. Are all the angles registered?

**Comment by redeboer** [comment]
Good point. Actually it's just a quick remark that had to be there while #122 is still out there.

Unfortunately, the PR preview does not render output, but from the `master` branch, I see [this](https://pwa.readthedocs.io/projects/tensorwaves/en/latest/usage/2_generate_data.html#2.4-Visualize-kinematic-variables):

```python
>>> data_set = kin.convert(data_sample)
>>> list(data_set.keys())
['mSq_2_3_4',
 'mSq_3_4',
 'mSq_2',
 'mSq_3',
 'mSq_4',
 'theta+3_4+2',
 'phi+3_4+2',
 'theta+3+4_vs_2',
 'phi+3+4_vs_2']
```

Meaning also only the angles of the relevant subsystems are generated. The best solution would be to create some `register_all_subsystem` method (to solve #122), just like ComPWA's [`createAllSubsystems`](https://compwa.github.io/ComPWA/classComPWA_1_1Physics_1_1HelicityFormalism_1_1HelicityKinematics.html#a9e6dca848564a15ff65f1af0fe8383b4). It's better to offer that as a method (not the default behaviour), because having all subsystems generated by default would create large data sets.

**Review by Leongrim — APPROVED** [review]

**Pull request merged**
