### PR TITLE
feat: add default dynamics RelativisticBW

### PR DESCRIPTION
**Pull request by redeboer**
Addresses #118, but does not close it. Since #116, dynamics are not provided from the recipe file, so we need some default.

### CODE REVIEW

**Comment by redeboer** [comment]
> if we want the same default behavior as before

For me this PR is just putting the finger in the dike: a bug fix that is not meant to tackle the bigger design.

**Comment by spflueger** [comment]
> > if we want the same default behavior as before
> 
> For me this PR is just putting the finger in the dike: a bug fix that is not meant to tackle the bigger design.

But like I said this version will not deliver the same results as before, since no the top node is also using a BW unless the user specifies that explicitly

**Comment by redeboer** [comment]
Yeah but that is already the case since #116: the program just dies because when it searches for non-existing dynamics.

**Comment by spflueger** [comment]
Ok, I was missing the info that non dynamics is still specified by the expert system on the top node by default. So the default behavior does stay the same. Not the prettiest bugfix though.

**Comment by redeboer** [comment]
Yes, so to my understanding, the expertsystem already adds 'non-dynamic' dynamics for the top node:
https://github.com/ComPWA/expertsystem/blob/94231dea8b200097edd1a8c8be1d56a5210a0735/expertsystem/amplitude/_yaml_adapter.py#L31-L36

It's super dirty, because this happens only for YAML, but we don't really want to support XML for `tensorwaves` anyway.

**Pull request merged**
